unstructured-updatefunctor: replaced std::array
This patch resolves compile errors in the unstructured update functor:
unstructuredupdatefunctor.h:105:37: error: implicit instantiation of
undefined template 'std::__1::array<Cell, 4>'

Solution: std::array is replaced by LibGeoDecomp's FixedArray implementation.